# Generated by Django 5.0.6 on 2024-05-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('phoneno', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
